// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDE6QUmAT2e0dFKasf-Dx6XObKi7qNMlI',
    appId: '1:257808244841:web:ef4839edcc6ed109dfc2f8',
    messagingSenderId: '257808244841',
    projectId: 'connexion-c038c',
    authDomain: 'connexion-c038c.firebaseapp.com',
    storageBucket: 'connexion-c038c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD4smlCe5fTYalNl9iOyiUOuNa0bPPXRA',
    appId: '1:257808244841:android:aa7a7b1a9ed96c5fdfc2f8',
    messagingSenderId: '257808244841',
    projectId: 'connexion-c038c',
    storageBucket: 'connexion-c038c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAtc5-adSoFnFeGyGRiANg4wlT9i1Ygpc',
    appId: '1:257808244841:ios:ddd5bf83b34754f0dfc2f8',
    messagingSenderId: '257808244841',
    projectId: 'connexion-c038c',
    storageBucket: 'connexion-c038c.appspot.com',
    iosClientId: '257808244841-vsodv8i0gr0ccfq620qvpgmhrvkr38o0.apps.googleusercontent.com',
    iosBundleId: 'com.example.connexion',
  );
}
